import Head from "next/head";
import Image from "next/image";
import Password from "../components/password";
import User from "../components/user";
import styles from "../styles/login.module.css";
import Inputs from "../components/inputs";


export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.body}>
        <div className={styles.left}>
          <div className={styles.centered}>
          <Image src='/assets/Icono Smart + Texto.svg' height={98} width={332} />
          <Inputs/>
          </div>
        </div>
        <div className={styles.right}>
          <div className={styles.centered}>
          <Image src='/assets/Ilustración - Inicio de sesión.svg' height={600} width={600} />
          </div>
        </div>
      </div>
    </div>
  );
}
